const demoJobs=[{id:"patient-ops",title:"Patient Operations Manager",company:"Example Pediatric Health",location:"New York, NY · Hybrid",salary:"$120K–$140K",fit:94,resume:"A",why:"Strong fit for healthcare operations, family-facing workflows, staffing coordination, process improvement and systems implementation."},{id:"business-ops",title:"Business Operations Manager",company:"Example Growth Company",location:"New York, NY · Hybrid",salary:"$115K–$135K",fit:91,resume:"B",why:"Strong fit for process design, workflow automation, project management, reporting, SOPs and cross-functional execution."},{id:"growth-ops",title:"Growth Operations Manager",company:"Example Health Tech",location:"Remote · US",salary:"$110K–$130K",fit:88,resume:"C",why:"Good match for CRM workflows, automation, reporting, funnel operations and growth enablement without making SEO the primary responsibility."}];
let jobs=JSON.parse(localStorage.getItem("kja_jobs"))||demoJobs;
let statuses=JSON.parse(localStorage.getItem("kja_statuses"))||{};
let criteria=JSON.parse(localStorage.getItem("kja_criteria"))||{minSalary:"100000",location:"NYC / Long Island / Remote"};
const jobsList=document.getElementById("jobsList"),appliedCount=document.getElementById("appliedCount"),matchCount=document.getElementById("matchCount"),topFitDisplay=document.getElementById("topFitDisplay"),minSalary=document.getElementById("minSalary"),locationPref=document.getElementById("locationPref"),minSalaryDisplay=document.getElementById("minSalaryDisplay"),saveCriteria=document.getElementById("saveCriteria"),saveMessage=document.getElementById("saveMessage"),resetDemo=document.getElementById("resetDemo"),installBtn=document.getElementById("installBtn");
function renderJobs(){jobsList.innerHTML="";jobs.forEach(job=>{const current=statuses[job.id]||"";const el=document.createElement("article");el.className="job-card";el.innerHTML=`<div class="job-top"><div><h4>${job.title}</h4><div class="company">${job.company}</div></div><span class="fit-badge">${job.fit}% fit</span></div><div class="meta"><span>${job.location}</span><span>${job.salary}</span></div><p>${job.why}</p><div class="resume-rec">Recommended Resume: <strong>${job.resume}</strong></div><div class="actions"><button class="action-btn ${current==="saved"?"selected":""}" data-job="${job.id}" data-status="saved">Save</button><button class="action-btn ${current==="skipped"?"selected":""}" data-job="${job.id}" data-status="skipped">Skip</button><button class="action-btn ${current==="applied"?"selected":""}" data-job="${job.id}" data-status="applied">Applied</button></div>`;jobsList.appendChild(el)});document.querySelectorAll(".action-btn").forEach(btn=>btn.addEventListener("click",()=>{statuses[btn.dataset.job]=btn.dataset.status;localStorage.setItem("kja_statuses",JSON.stringify(statuses));renderJobs()}));matchCount.textContent=jobs.length;topFitDisplay.textContent=jobs.length?Math.max(...jobs.map(j=>j.fit))+"%":"—";appliedCount.textContent=Object.values(statuses).filter(v=>v==="applied").length}
function applyCriteriaToUI(){minSalary.value=criteria.minSalary;locationPref.value=criteria.location;minSalaryDisplay.textContent="$"+(Number(criteria.minSalary)/1000)+"K"}
saveCriteria.addEventListener("click",()=>{criteria={minSalary:minSalary.value,location:locationPref.value};localStorage.setItem("kja_criteria",JSON.stringify(criteria));applyCriteriaToUI();saveMessage.textContent="Preferences saved on this device.";setTimeout(()=>saveMessage.textContent="",2200)});
resetDemo.addEventListener("click",()=>{jobs=demoJobs;statuses={};localStorage.setItem("kja_jobs",JSON.stringify(jobs));localStorage.setItem("kja_statuses",JSON.stringify(statuses));renderJobs()});
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove("hidden")});installBtn.addEventListener("click",async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add("hidden")});
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"))}
applyCriteriaToUI();renderJobs();